### ISSUE TITLE
The db history topic or its content is fully or partially missing. Please check database history topic configuration and re-execute the snapshot.

### ISSUE THREAD

**Issue by JuchangGit** [apache/flink-cdc#1737]
**The db history topic or its content is fully or partially missing**
The db history topic or its content is fully or partially missing. Please check database history topic configuration and re-execute the snapshot.

**Environment :**
 - Flink version :  1.16.0
 - Flink CDC version: 2.3.0
 - Database and version: oracle19c

**flink-sql**
CREATE TABLE SOURCE_PHOTO_TEST1 (
USERID STRING, 
USERNAME STRING, 
REALNAME STRING, 
ENNAME STRING, 
PRIMARY KEY(USERID) NOT ENFORCED
) WITH (
'connector' = 'oracle-cdc',
'hostname' = '127.0.0.1',
'port' = '1521',
'username' = 'C##FLINKUSER',
'password' = 'flinkpw',
'database-name' = 'ORCL',
'debezium.database.pdb.name' = 'ORCLPDB',
'schema-name' = 'FLINK1',
'table-name' = 'SOURCE_PHOTO_TEST',
'debezium.log.mining.strategy' = 'online_catalog',
'scan.incremental.snapshot.enabled' = 'true',
'scan.startup.mode' = 'initial'
);

**Exception log**
2022-11-13 16:06:12,227 WARN  io.debezium.relational.history.DatabaseHistoryMetrics        [] - Unable to register the MBean 'debezium.oracle:type=connector-metrics,context=schema-history,server=oracle_logminer': debezium.oracle:type=connector-metrics,context=schema-history,server=oracle_logminer
2022-11-13 16:06:12,228 ERROR org.apache.flink.connector.base.source.reader.fetcher.SplitFetcherManager [] - Received uncaught exception.
java.lang.RuntimeException: SplitFetcher thread 0 received unexpected exception while polling the records
        at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:150) ~[flink-connector-files-1.16.0.jar:1.16.0]
        at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:105) [flink-connector-files-1.16.0.jar:1.16.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_221]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_221]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: io.debezium.DebeziumException: The db history topic or its content is fully or partially missing. Please check database history topic configuration and re-execute the snapshot.
        at io.debezium.relational.HistorizedRelationalDatabaseSchema.recover(HistorizedRelationalDatabaseSchema.java:47) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
        at com.ververica.cdc.connectors.oracle.source.reader.fetch.OracleSourceFetchTaskContext.validateAndLoadDatabaseHistory(OracleSourceFetchTaskContext.java:229) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
        at com.ververica.cdc.connectors.oracle.source.reader.fetch.OracleSourceFetchTaskContext.configure(OracleSourceFetchTaskContext.java:105) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
        at com.ververica.cdc.connectors.base.source.reader.external.IncrementalSourceStreamFetcher.submitTask(IncrementalSourceStreamFetcher.java:81) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
        at com.ververica.cdc.connectors.base.source.reader.IncrementalSourceSplitReader.checkSplitOrStartNext(IncrementalSourceSplitReader.java:138) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
        at com.ververica.cdc.connectors.base.source.reader.IncrementalSourceSplitReader.fetch(IncrementalSourceSplitReader.java:70) ~[flink-sql-connector-oracle-cdc-2.3.0.jar:2.3.0]
        at org.apache.flink.connector.base.source.reader.fetcher.FetchTask.run(FetchTask.java:58) ~[flink-connector-files-1.16.0.jar:1.16.0]
        at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:142) ~[flink-connector-files-1.16.0.jar:1.16.0]
        ... 6 more
2022-11-13 16:06:12,228 INFO  com.ververica.cdc.connectors.base.source.reader.IncrementalSourceSplitReader [] - Close current fetcher com.ververica.cdc.connectors.base.source.reader.external.IncrementalSourceStreamFetcher
2022-11-13 16:06:12,228 WARN  com.ververica.cdc.connectors.base.source.reader.external.IncrementalSourceStreamFetcher [] - Failed to close the stream fetcher in 30 seconds.

**Comment by caiiiookk** [comment]
I've encountered the same problem (almost the same Environment except for flink 1.15.3).
For me the root of it is that connections that are used in IncrementalSource are not set to PDB, so IncrementalSource.createEnumerator:139 cannot discover the table required. 
If you fix that then you'll start getting "ORA-00942: table or view does not exist" all over the place (for the same reason that connections aren't set to PDB)

**Comment by Archie-selfless** [comment]
I also faced this problem with following env:
- Flink 1.15.3 & 1.15.2
- FlinkCDC 2.3.0
- Oracle 11g

**Comment by GOODBOY008** [comment]
I will take a look this issue.

**Comment by yhz123** [comment]
The db history topic or its content is fully or partially missing

**Comment by yhz123** [comment]
请问大佬修复此问题了吗，是不是因为oracle某个表是分区表导致的这个问题实时增量抽取不了

**Comment by yhz123** [comment]
> 请问大佬修复此问题了吗，是不是因为oracle某个表是分区表导致的这个问题实时增量抽取不了

**Comment by Powww** [comment]
就是分区表不行，后来通过源码修复，分区表可以了，但是还有其他很多问题，最后我们觉得Flink oracle CDC没有达到生产环境可用的成熟度。

**Comment by GOODBOY008** [comment]
> 就是分区表不行，后来通过源码修复，分区表可以了，但是还有其他很多问题，最后我们觉得Flink oracle CDC没有达到生产环境可用的成熟度。

@Powww 你好，我提供一个基于dbz版本是1.9.7 的jar，帮忙验证下。

**Comment by spoon-lz** [comment]
@GOODBOY008 你好，我们使用oracle-cdc 也遇到了这个问题，请问是否有解决的办法呢

**Comment by lafang2009** [comment]
@leonardBang  @ruanhang1993  大佬，这个bug还修复吗？我看已经从V2.4.0中移除了。。

**Comment by ruanhang1993** [comment]
It seems like the problem still exists and not fixed by the update of debezium version. Move this to 2.5.0.

**Comment by zzfzhou** [comment]
这个bug在2.4.1仍然存在，请问如何处理
![image](https://github.com/ververica/flink-cdc-connectors/assets/31532517/7f2411dd-0211-46c6-9eb7-cb4591d50b4f)

**Comment by fangchuanming** [comment]
i also meet this problem, give one  useful solution: because of i create a table in orcacle APEX database,  when begin to run oracle cdc, its will runtimeExcetion:
```
Caused by: org.apache.inlong.sort.cdc.oracle.shaded.io.debezium.DebeziumException: The db history topic or its content is fully or partially missing. Please check database history topic configuration and re-execute the snapshot.

```
later, i change create my table in my self oracle database, it's woker well.

and i find that APEX_030200 is the APEX product database user. maybe this database is something specials
```
https://www.oracle.com/ocom/groups/public/@otn/documents/webcontent/217843.htm
```

**Comment by GOODBOY008** [comment]
> 2.4.1 还是有这个问题， @GOODBOY008 有空看看吗？
@melin 
If  your table is partitioned , you can use this pr https://github.com/ververica/flink-cdc-connectors/pull/2479.

**Comment by GOODBOY008** [comment]
> > > 2.4.1 还是有这个问题， @GOODBOY008 有空看看吗？
> > > @melin
> > > If  your table is partitioned , you can use this pr https://github.com/ververica/flink-cdc-connectors/pull/2479.
> 
> 我的测试表不是分区表，这个改动，应该解决不了我遇到的问题。我直接查询sql，能够找到我同步的表： ![image](https://user-images.githubusercontent.com/1145830/274797811-8f9a2a1e-dd96-4b49-8b34-cab59b245865.png)

You oracle running model is cdb or nocdb ?

**Comment by lvyanquan** [comment]
@melin hi, can you show how this table was created in oracle using SELECT DBMS_METADATA.GET_DDL（Hide sensitive information）？

**Comment by lvyanquan** [comment]
Is it under SYSTEM TABLESPACE? can you find this table using 
```
 SELECT OWNER ,TABLE_NAME, TABLESPACE_NAME FROM ALL_TABLES
 WHERE TABLESPACE_NAME IS NOT NULL AND TABLESPACE_NAME NOT IN ('SYSTEM','SYSAUX');

```

**Comment by aiwenmo** [comment]
I encountered this issue and I avoided it by modifying the source code of Debezium. The implementation principle is that OracleCDC only scans and captures whitelist tables. Next, I will submit this optimization.

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
