### ISSUE TITLE
Caused by: io.debezium.DebeziumException: could not find next log; 

### ISSUE THREAD

**Issue by zZxiaowang** [apache/flink-cdc#1794]
**Describe the bug(Please use English)*An error was reported when the database was manually backed up*

**Environment :**
 - Flink version :  1.14.3
 - Flink CDC version: 2.2.1
 - Database and version: 5.7

**To Reproduce**
1. The test data :
2. The test code :
3. The error :
An error was reported when the database was manually backed up.I have privileges like : select_priv, repl_slave_priv ,repl_client_priv,
when I use cdc sync the MySql tables  and the database was manually backed up together ,  this error occured.

**Additional Description**

Caused by: io.debezium.DebeziumException: could not find next log; the first event 'Storage.000086' at 57144201, the last event read from '/bak/binlog/Storage.000086' at 101689506, the last byte read from '/bak/binlog/Storage.000086' at 101689506. Error code: 1236; SQLSTATE: HY000.
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.wrap(MySqlStreamingChangeEventSource.java:1146) ~[stationcmdsync.jar:?]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$ReaderThreadLifecycleListener.onCommunicationFailure(MySqlStreamingChangeEventSource.java:1185) ~[stationcmdsync.jar:?]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:973) ~[stationcmdsync.jar:?]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:606) ~[stationcmdsync.jar:?]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:850) ~[stationcmdsync.jar:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_161]
Caused by: com.github.shyiko.mysql.binlog.network.ServerException: could not find next log; the first event 'Storage.000086' at 57144201, the last event read from '/bak/binlog/Storage.000086' at 101689506, the last byte read from '/bak/binlog/Storage.000086' at 101689506.
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:937) ~[stationcmdsync.jar:?]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:606) ~[stationcmdsync.jar:?]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:850) ~[stationcmdsync.jar:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_161]
2022-12-03 02:29:06,382 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - Job Flink Streaming Job (b2ea26f12c5fb818e236c64b660bb7e6) switched from state FAILING to FAILED.
org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:138) ~[flink-dist_2.12-1.14.3.jar:1.14.3]
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:82) ~[flink-dist_2.12-1.14.3.jar:1.14.3]
	at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:252) ~[flink-dist_2.12-1.14.3.jar:1.14.3]
	at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:242) ~[flink-dist_2.12-1.14.3.jar:1.14.3]
	at org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:233) ~[flink-dist_2.12-1.14.3.jar:1.14.3]
	at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:684) ~[flink-dist_2.12-1.14.3.jar:1.14.3]
	at org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:79) ~[flink-dist_2.12-1.14.3.jar:1.14.3]
	at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:444) ~[flink-dist_2.12-1.14.3.jar:1.14.3]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.lambda$handleRpcInvocation$1(AkkaRpcActor.java:316) ~[flink-rpc-akka_6df5e012-1a24-4269-9837-b1b94fb7d977.jar:1.14.3]
	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:83) ~[flink-rpc-akka_6df5e012-1a24-4269-9837-b1b94fb7d977.jar:1.14.3]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:314) ~[flink-rpc-akka_6df5e012-1a24-4269-9837-b1b94fb7d977.jar:1.14.3]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:217) ~[flink-rpc-akka_6df5e012-1a24-4269-9837-b1b94fb7d977.jar:1.14.3]
	at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:78) ~[flink-rpc-akka_6df5e012-1a24-4269-9837-b1b94fb7d977.jar:1.14.3]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:163) ~[flink-rpc-akka_6df5e012-1a24-4269-9837-b1b94fb7d977.jar:1.14.3]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24) [flink-rpc-akka_6df5e012-1a24-4269-9837-b1b94fb7d977.jar:1.14.3]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20) [flink-rpc-akka_6df5e012-1a24-4269-9837-b1b94fb7d977.jar:1.14.3]
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:123) [flink-rpc-akka_6df5e012-1a24-4269-9837-b1b94fb7d977.jar:1.14.3]
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:122) [flink-rpc-akka_6df5e012-1a24-4269-9837-b1b94fb7d977.jar:1.14.3]
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20) [flink-rpc-akka_6df5e012-1a24-4269-9837-b1b94fb7d977.jar:1.14.3]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) [flink-rpc-akka_6df5e012-1a24-4269-9837-b1b94fb7d977.jar:1.14.3]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172) [flink-rpc-akka_6df5e012-1a24-4269-9837-b1b94fb7d977.jar:1.14.3]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172) [flink-rpc-akka_6df5e012-1a24-4269-9837-b1b94fb7d977.jar:1.14.3]
	at akka.actor.Actor.aroundReceive(Actor.scala:537) [flink-rpc-akka_6df5e012-1a24-4269-9837-b1b94fb7d977.jar:1.14.3]
	at akka.actor.Actor.aroundReceive$(Actor.scala:535) [flink-rpc-akka_6df5e012-1a24-4269-9837-b1b94fb7d977.jar:1.14.3]
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220) [flink-rpc-akka_6df5e012-1a24-4269-9837-b1b94fb7d977.jar:1.14.3]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580) [flink-rpc-akka_6df5e012-1a24-4269-9837-b1b94fb7d977.jar:1.14.3]
	at akka.actor.ActorCell.invoke(ActorCell.scala:548) [flink-rpc-akka_6df5e012-1a24-4269-9837-b1b94fb7d977.jar:1.14.3]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270) [flink-rpc-akka_6df5e012-1a24-4269-9837-b1b94fb7d977.jar:1.14.3]
	at akka.dispatch.Mailbox.run(Mailbox.scala:231) [flink-rpc-akka_6df5e012-1a24-4269-9837-b1b94fb7d977.jar:1.14.3]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243) [flink-rpc-akka_6df5e012-1a24-4269-9837-b1b94fb7d977.jar:1.14.3]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_161]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_161]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_161]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_161]

**Comment by zZxiaowang** [comment]
If I configure restart for the program ,the program will restart once ,then  it runs suitably.Is the backups affects CDC?

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
