### ISSUE TITLE
flink-sql-connector-tidb-cdc全量同步数据后，flink job退出无法增量同步

### ISSUE THREAD

**Issue by tiannan-sr** [apache/flink-cdc#1831]
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.15.2
 - Flink CDC version: flink-sql-connector-tidb-cdc-2.3.0.jar
 - Database and version: TiDB v6.4.0

**To Reproduce**
1. 在Tidb中建库建表写入数据 :
```
CREATE TABLE person (
id INT(11) primary key,
name VARCHAR(255),
birthday DATE
);
INSERT INTO person VALUES(1,'tom','20170912');
INSERT INTO person(id,name) VALUES('2','bob');
```

2. 启动flink集群，通过cdc将TiDB中库、表及数据全量同步到下游数据库完成 :
3. flink job完成后自动退出，无法完成后面的增量数据同步；
4. flink standalonesession日志中有如下报错 :
```
2022-12-15 20:05:32,366 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - Source: person_src[1] (1/1) (c0f5920df0fc454fe258a678bc3f11bb) switched from RUNNING to FAILED on localhost:43103-4ca082 @ localhost (dataPort=39532).
java.lang.IllegalArgumentException: Invalid range: [+INF..{116,128,0,255,255,255,255,255,254})
	at org.apache.flink.shaded.guava30.com.google.common.collect.Range.<init>(Range.java:358) ~[flink-sql-connector-tidb-cdc-2.3.0.jar:2.3.0]
	at org.apache.flink.shaded.guava30.com.google.common.collect.Range.create(Range.java:156) ~[flink-sql-connector-tidb-cdc-2.3.0.jar:2.3.0]
	at org.apache.flink.shaded.guava30.com.google.common.collect.Range.closedOpen(Range.java:193) ~[flink-sql-connector-tidb-cdc-2.3.0.jar:2.3.0]
	at org.tikv.cdc.CDCClient.overlapWithRegion(CDCClient.java:230) ~[flink-sql-connector-tidb-cdc-2.3.0.jar:2.3.0]
	at org.tikv.cdc.CDCClient.addRegions(CDCClient.java:185) ~[flink-sql-connector-tidb-cdc-2.3.0.jar:2.3.0]
	at org.tikv.cdc.CDCClient.applyKeyRange(CDCClient.java:178) ~[flink-sql-connector-tidb-cdc-2.3.0.jar:2.3.0]
	at org.tikv.cdc.CDCClient.start(CDCClient.java:98) ~[flink-sql-connector-tidb-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction.run(TiKVRichParallelSourceFunction.java:165) ~[flink-sql-connector-tidb-cdc-2.3.0.jar:2.3.0]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:67) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:332) ~[flink-dist-1.15.2.jar:1.15.2]
2022-12-15 20:05:32,378 INFO  org.apache.flink.runtime.executiongraph.failover.flip1.RestartPipelinedRegionFailoverStrategy [] - Calculating tasks to restart to recover the failed task bc764cd8ddf7a0cff126f51c16239658_0.
2022-12-15 20:05:32,379 INFO  org.apache.flink.runtime.executiongraph.failover.flip1.RestartPipelinedRegionFailoverStrategy [] - 2 tasks should be restarted to recover the failed task bc764cd8ddf7a0cff126f51c16239658_0.
2022-12-15 20:05:32,381 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - Job insert-into_default_catalog.flink_test.person_sink (a6f1f409f5f2ebac76d755f088bb3aa3) switched from state RUNNING to FAILING.
org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:138) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:82) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:301) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:291) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:282) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:739) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:78) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:443) ~[flink-dist-1.15.2.jar:1.15.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.lambda$handleRpcInvocation$1(AkkaRpcActor.java:304) ~[flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:83) ~[flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:302) ~[flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:217) ~[flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:78) ~[flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:163) ~[flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:123) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:122) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at akka.actor.Actor.aroundReceive(Actor.scala:537) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at akka.actor.Actor.aroundReceive$(Actor.scala:535) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at akka.actor.ActorCell.invoke(ActorCell.scala:548) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at akka.dispatch.Mailbox.run(Mailbox.scala:231) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_252]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_252]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_252]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_252]
Caused by: java.lang.IllegalArgumentException: Invalid range: [+INF..{116,128,0,255,255,255,255,255,254})
	at org.apache.flink.shaded.guava30.com.google.common.collect.Range.<init>(Range.java:358) ~[flink-sql-connector-tidb-cdc-2.3.0.jar:2.3.0]
	at org.apache.flink.shaded.guava30.com.google.common.collect.Range.create(Range.java:156) ~[flink-sql-connector-tidb-cdc-2.3.0.jar:2.3.0]
	at org.apache.flink.shaded.guava30.com.google.common.collect.Range.closedOpen(Range.java:193) ~[flink-sql-connector-tidb-cdc-2.3.0.jar:2.3.0]
	at org.tikv.cdc.CDCClient.overlapWithRegion(CDCClient.java:230) ~[flink-sql-connector-tidb-cdc-2.3.0.jar:2.3.0]
	at org.tikv.cdc.CDCClient.addRegions(CDCClient.java:185) ~[flink-sql-connector-tidb-cdc-2.3.0.jar:2.3.0]
	at org.tikv.cdc.CDCClient.applyKeyRange(CDCClient.java:178) ~[flink-sql-connector-tidb-cdc-2.3.0.jar:2.3.0]
	at org.tikv.cdc.CDCClient.start(CDCClient.java:98) ~[flink-sql-connector-tidb-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction.run(TiKVRichParallelSourceFunction.java:165) ~[flink-sql-connector-tidb-cdc-2.3.0.jar:2.3.0]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:67) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:332) ~[flink-dist-1.15.2.jar:1.15.2]
2022-12-15 20:05:32,384 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - ChangelogNormalize[3] -> ConstraintEnforcer[4] -> Sink: person_sink[4] (1/1) (02e22d3f11f96a24e1018aeed4b50fdf) switched from RUNNING to CANCELING.
2022-12-15 20:05:32,648 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - ChangelogNormalize[3] -> ConstraintEnforcer[4] -> Sink: person_sink[4] (1/1) (02e22d3f11f96a24e1018aeed4b50fdf) switched from CANCELING to CANCELED.
2022-12-15 20:05:32,650 INFO  org.apache.flink.runtime.resourcemanager.slotmanager.DeclarativeSlotManager [] - Clearing resource requirements of job a6f1f409f5f2ebac76d755f088bb3aa3
2022-12-15 20:05:32,650 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - Job insert-into_default_catalog.flink_test.person_sink (a6f1f409f5f2ebac76d755f088bb3aa3) switched from state FAILING to FAILED.
org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:138) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:82) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:301) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:291) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:282) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:739) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:78) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:443) ~[flink-dist-1.15.2.jar:1.15.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.lambda$handleRpcInvocation$1(AkkaRpcActor.java:304) ~[flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:83) ~[flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:302) ~[flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:217) ~[flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:78) ~[flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:163) ~[flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:123) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:122) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at akka.actor.Actor.aroundReceive(Actor.scala:537) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at akka.actor.Actor.aroundReceive$(Actor.scala:535) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at akka.actor.ActorCell.invoke(ActorCell.scala:548) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at akka.dispatch.Mailbox.run(Mailbox.scala:231) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243) [flink-rpc-akka_6e3ce497-489a-418b-94f9-8c90ba422693.jar:1.15.2]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_252]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_252]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_252]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_252]
Caused by: java.lang.IllegalArgumentException: Invalid range: [+INF..{116,128,0,255,255,255,255,255,254})
	at org.apache.flink.shaded.guava30.com.google.common.collect.Range.<init>(Range.java:358) ~[flink-sql-connector-tidb-cdc-2.3.0.jar:2.3.0]
	at org.apache.flink.shaded.guava30.com.google.common.collect.Range.create(Range.java:156) ~[flink-sql-connector-tidb-cdc-2.3.0.jar:2.3.0]
	at org.apache.flink.shaded.guava30.com.google.common.collect.Range.closedOpen(Range.java:193) ~[flink-sql-connector-tidb-cdc-2.3.0.jar:2.3.0]
	at org.tikv.cdc.CDCClient.overlapWithRegion(CDCClient.java:230) ~[flink-sql-connector-tidb-cdc-2.3.0.jar:2.3.0]
	at org.tikv.cdc.CDCClient.addRegions(CDCClient.java:185) ~[flink-sql-connector-tidb-cdc-2.3.0.jar:2.3.0]
	at org.tikv.cdc.CDCClient.applyKeyRange(CDCClient.java:178) ~[flink-sql-connector-tidb-cdc-2.3.0.jar:2.3.0]
	at org.tikv.cdc.CDCClient.start(CDCClient.java:98) ~[flink-sql-connector-tidb-cdc-2.3.0.jar:2.3.0]
	at com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction.run(TiKVRichParallelSourceFunction.java:165) ~[flink-sql-connector-tidb-cdc-2.3.0.jar:2.3.0]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:67) ~[flink-dist-1.15.2.jar:1.15.2]
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:332) ~[flink-dist-1.15.2.jar:1.15.2]
2022-12-15 20:05:32,651 INFO  org.apache.flink.runtime.checkpoint.CheckpointCoordinator    [] - Stopping checkpoint coordinator for job a6f1f409f5f2ebac76d755f088bb3aa3.
2022-12-15 20:05:32,659 INFO  org.apache.flink.runtime.dispatcher.StandaloneDispatcher     [] - Job a6f1f409f5f2ebac76d755f088bb3aa3 reached terminal state FAILED.
org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:138)
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:82)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:301)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:291)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:282)
	at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:739)
	at org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:78)
	at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:443)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.lambda$handleRpcInvocation$1(AkkaRpcActor.java:304)
	at org.apache.flink.runtime.concurrent.akka.ClassLoadingUtils.runWithContextClassLoader(ClassLoadingUtils.java:83)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:302)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:217)
	at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:78)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:163)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:24)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:20)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:123)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:122)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:20)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:220)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.IllegalArgumentException: Invalid range: [+INF..{116,128,0,255,255,255,255,255,254})
	at org.apache.flink.shaded.guava30.com.google.common.collect.Range.<init>(Range.java:358)
	at org.apache.flink.shaded.guava30.com.google.common.collect.Range.create(Range.java:156)
	at org.apache.flink.shaded.guava30.com.google.common.collect.Range.closedOpen(Range.java:193)
	at org.tikv.cdc.CDCClient.overlapWithRegion(CDCClient.java:230)
	at org.tikv.cdc.CDCClient.addRegions(CDCClient.java:185)
	at org.tikv.cdc.CDCClient.applyKeyRange(CDCClient.java:178)
	at org.tikv.cdc.CDCClient.start(CDCClient.java:98)
	at com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction.run(TiKVRichParallelSourceFunction.java:165)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:67)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:332)
2022-12-15 20:05:32,678 INFO  org.apache.flink.runtime.dispatcher.StandaloneDispatcher     [] - Job a6f1f409f5f2ebac76d755f088bb3aa3 has been registered for cleanup in the JobResultStore after reaching a terminal state.
2022-12-15 20:05:32,680 INFO  org.apache.flink.runtime.jobmaster.JobMaster                 [] - Stopping the JobMaster for job 'insert-into_default_catalog.flink_test.person_sink' (a6f1f409f5f2ebac76d755f088bb3aa3).
2022-12-15 20:05:32,682 INFO  org.apache.flink.runtime.checkpoint.StandaloneCompletedCheckpointStore [] - Shutting down
2022-12-15 20:05:32,683 INFO  org.apache.flink.runtime.jobmaster.slotpool.DefaultDeclarativeSlotPool [] - Releasing slot [ed92788a840fcf09a5a2e48b1b8c08de].
2022-12-15 20:05:32,683 INFO  org.apache.flink.runtime.jobmaster.JobMaster                 [] - Close ResourceManager connection 6d621829a267bba9075569c1cc5c0a4a: Stopping JobMaster for job 'insert-into_default_catalog.flink_test.person_sink' (a6f1f409f5f2ebac76d755f088bb3aa3).
2022-12-15 20:05:32,684 INFO  org.apache.flink.runtime.resourcemanager.StandaloneResourceManager [] - Disconnect job manager 00000000000000000000000000000000@akka.tcp://flink@localhost:6124/user/rpc/jobmanager_2 for job a6f1f409f5f2ebac76d755f088bb3aa3 from the resource manager.
```

@leonardBang 可否帮忙看看
**Additional Description**

**Comment by zhangzhaohuazai** [comment]
How is it going now？

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
