### ISSUE TITLE
simple tidb cdc demo,but caused 'java.lang.IllegalArgumentException: Invalid range: '

### ISSUE THREAD

**Issue by Cqz666** [apache/flink-cdc#1872]
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.14.5
 - Flink CDC version: 2.4-SNAPSHOT
 - Database and version: TIDB v5.3.1

**To Reproduce**
1. The test data :
2. The test code :
 CREATE TABLE tidb_source (
id INT,
name STRING,
description STRING,
PRIMARY KEY (id) NOT ENFORCED
) WITH (
    'connector' = 'tidb-cdc',
    'tikv.grpc.timeout_in_ms' = '20000',
    'pd-addresses' = '127.0.1.1:2379',
    'database-name' = 'test',
    'table-name' = 'products'
);
CREATE TABLE sink (
id INT,
name STRING,
description STRING,
PRIMARY KEY (id) NOT ENFORCED
) WITH (
    'connector' = 'print'
);
        stEnv.executeSql(sourcre);
        stEnv.executeSql(sink);
        TableResult result =
                stEnv.executeSql(
                        "INSERT INTO sink select `id`, name, description FROM tidb_source t");
        result.print();

4. The error :

Caused by: java.lang.IllegalArgumentException: Invalid range: [+INF..{116,128,0,0,0,0,0,0,57,95,114,85,85,85,85,85,85,85,84})
	at org.apache.flink.shaded.guava30.com.google.common.collect.Range.<init>(Range.java:358)
	at org.apache.flink.shaded.guava30.com.google.common.collect.Range.create(Range.java:156)
	at org.apache.flink.shaded.guava30.com.google.common.collect.Range.intersection(Range.java:558)
	at org.tikv.cdc.CDCClient.overlapWithRegion(CDCClient.java:235)
	at org.tikv.cdc.CDCClient.addRegions(CDCClient.java:185)
	at org.tikv.cdc.CDCClient.applyKeyRange(CDCClient.java:178)
	at org.tikv.cdc.CDCClient.start(CDCClient.java:98)
	at com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction.run(TiKVRichParallelSourceFunction.java:165)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:67)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:323)

**Additional Description**

**Comment by Cqz666** [comment]
@leonardBang help plz !

**Comment by zhangzhaohuazai** [comment]
I meet the error too:
`java.lang.IllegalArgumentException: Invalid range: [+INF..{116,128,0,0,0,0,0,3,162,95,114,63,255,255,255,255,255,255,254})`

**Comment by hbk671104** [comment]
same error. please help.

<img width="1858" alt="企业微信截图_168169783555" src="https://user-images.githubusercontent.com/5074788/232362839-1506132d-a25b-43a9-a83e-2b716c7d37f5.png">

**Comment by zhangzhaohuazai** [comment]
How is it going now？

**Comment by PatrickRen** [comment]
Closing this issue as it has been migrated to [Apache Jira](https://issues.apache.org/jira).
