### ISSUE TITLE
TiDb 大表同步出现NullPointerException

### ISSUE THREAD

**Issue by 524687460** [apache/flink-cdc#2198]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

Flink1.14

### Flink CDC version

2.3.0

### Database and its version

TiDb 6.1.5

### Minimal reproduce step

大表同步

### What did you expect to see?

没有错误

### What did you see instead?

java.lang.NullPointerException
	at java.util.concurrent.LinkedBlockingQueue.offer(LinkedBlockingQueue.java:411)
	at com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction.flushRows(TiKVRichParallelSourceFunction.java:266)
	at com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction.readChangeEvents(TiKVRichParallelSourceFunction.java:253)
	at com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction.run(TiKVRichParallelSourceFunction.java:172)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:67)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:323)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by 524687460** [comment]
![捕获](https://github.com/ververica/flink-cdc-connectors/assets/12776002/00817818-56be-4c8e-82ba-011b3fcf59d6)
是否可以再这段代码增加null判断

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
