### ISSUE TITLE
[Bug] sqlserver-cdc 执行过程中偶尔报错

### ISSUE THREAD

**Issue by ysq5202121** [apache/flink-cdc#2420]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.2

### Flink CDC version

flink-sql-connector-sqlserver-cdc-2.5-SNAPSHOT

### Database and its version

sqlserver2014

### Minimal reproduce step

执行过程中，偶尔会出现，不是每次

### What did you expect to see?

希望别报错

### What did you see instead?

2023-08-22 04:20:47
java.lang.RuntimeException: One or more fetchers have encountered exception
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcherManager.checkErrors(SplitFetcherManager.java:225)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.getNextFetch(SourceReaderBase.java:169)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:130)
	at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:385)
	at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:68)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:545)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:231)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:836)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:785)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:935)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:914)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:728)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:550)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: SplitFetcher thread 0 received unexpected exception while polling the records
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:150)
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:50)
	at io.debezium.connector.sqlserver.SqlServerStreamingChangeEventSource.executeIteration(SqlServerStreamingChangeEventSource.java:459)
	at io.debezium.connector.sqlserver.SqlServerStreamingChangeEventSource.execute(SqlServerStreamingChangeEventSource.java:138)
	at com.ververica.cdc.connectors.sqlserver.source.reader.fetch.SqlServerStreamFetchTask$LsnSplitReadTask.execute(SqlServerStreamFetchTask.java:160)
	at com.ververica.cdc.connectors.sqlserver.source.reader.fetch.SqlServerStreamFetchTask.execute(SqlServerStreamFetchTask.java:70)
	at com.ververica.cdc.connectors.base.source.reader.external.IncrementalSourceStreamFetcher.lambda$submitTask$0(IncrementalSourceStreamFetcher.java:89)
	... 5 more
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: No route to host (Read failed)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:3422)
	at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:2066)
	at com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6616)
	at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:7802)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:896)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:793)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7417)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3488)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:237)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeQuery(SQLServerStatement.java:715)
	at io.debezium.jdbc.JdbcConnection.queryAndMap(JdbcConnection.java:641)
	at io.debezium.jdbc.JdbcConnection.queryAndMap(JdbcConnection.java:510)
	at io.debezium.connector.sqlserver.SqlServerConnection.getMaxTransactionLsn(SqlServerConnection.java:274)
	at io.debezium.connector.sqlserver.SqlServerStreamingChangeEventSource.getToLsn(SqlServerStreamingChangeEventSource.java:614)
	at io.debezium.connector.sqlserver.SqlServerStreamingChangeEventSource.executeIteration(SqlServerStreamingChangeEventSource.java:202)
	... 9 more
Caused by: java.net.SocketException: No route to host (Read failed)
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:2058)
	... 23 more

### Anything else?

如果出现上面问题，造成CDC无法清除历史数据（貌似锁住了）
(@P0 varbinary(8000),@P1 varbinary(8000))
SELECT *, TODATETIMEOFFSET([AukeysDataWarehouse].sys.fn_cdc_map_lsn_to_time([__$start_lsn]), DATEPART(TZOFFSET, SYSDATETIMEOFFSET())) 
FROM [AukeysDataWarehouse].cdc.[fn_cdc_get_all_changes_dbo_GP_ListingProfit](@P0, @P1, N'all update old') 
order by [__$start_lsn] ASC, [__$seqval] ASC, [__$operation] ASC
上面是执行的语句，一直卡住

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by GOODBOY008** [comment]
@ysq5202121 The issue had fix in master , compile on your local.

**Comment by ysq5202121** [comment]
@GOODBOY008  基本上开始的时候有，现在基本上没有出现

**Comment by edmond-kk** [comment]
@GOODBOY008  The same issue sometimes hinders the execution of the sp_MScdc_cleanup_job in SQL Server. Additionally, does SQL Server CDC support retrying in case of network exceptions? (For example, if a SQLServerException: "No route to host" or a "timeout" occurs, currently this exception causes the job to fail directly.) This issue is particularly noticeable when not using the incremental snapshot framework.

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
