### ISSUE TITLE
[Bug] [sqlserver cdc] incremental snapshot phase restore from checkpoint throw NullPointerException

### ISSUE THREAD

**Issue by edmond-kk** [apache/flink-cdc#2536]
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.13.6

### Flink CDC version

2.5-SNAPSHOT

### Database and its version

sqlserver 2016

### Minimal reproduce step

使用公司表跑任务时偶发出现，表数据量约1.3e，暂时不知道如何在本地复现。

### What did you expect to see?

任务可以正常通过checkpoint恢复

### What did you see instead?

任务偶尔会因为异常【Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: 为过程或函数 cdc.fn_cdc_get_all_changes_ ...  提供的参数数目不足。】 挂掉，但因为可以从checkpoint自动恢复，所以之前没去看该异常原因。
但有时无法从checkpoint恢复，异常日志：
2023-10-08 09:28:03,608 ERROR org.apache.flink.runtime.source.coordinator.SourceCoordinator [] - Uncaught exception in the SplitEnumerator for Source Source: primaryTableSource while handling operator event RequestSplitEvent (host='10.244.1.67') from subtask 1. Triggering job failover.
org.apache.flink.util.FlinkRuntimeException: Failed to assign splits {0=[SnapshotSplit{tableId=CRDB.dbo.tCR0001_V2.0, splitId='CRDB.dbo.tCR0001_V2.0:875', splitKeyType=[`ID` BIGINT NOT NULL], splitStart=[87508751], splitEnd=[87608761], highWatermark=null}]} due to 
	at org.apache.flink.runtime.source.coordinator.SourceCoordinatorContext.callInCoordinatorThread(SourceCoordinatorContext.java:388) ~[flink-dist_2.11-1.13.6.jar:1.13.6]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinatorContext.assignSplits(SourceCoordinatorContext.java:176) ~[flink-dist_2.11-1.13.6.jar:1.13.6]
	at org.apache.flink.api.connector.source.SplitEnumeratorContext.assignSplit(SplitEnumeratorContext.java:82) ~[flink-dist_2.11-1.13.6.jar:1.13.6]
	at com.ververica.cdc.connectors.base.source.enumerator.IncrementalSourceEnumerator.assignSplits(IncrementalSourceEnumerator.java:177) ~[blob_p-b4f6d17e0c08bbb487e958e0b3e0e49c0ab04224-e97c463e6ea3a571bf45208735d22f4e:?]
	at com.ververica.cdc.connectors.base.source.enumerator.IncrementalSourceEnumerator.handleSplitRequest(IncrementalSourceEnumerator.java:97) ~[blob_p-b4f6d17e0c08bbb487e958e0b3e0e49c0ab04224-e97c463e6ea3a571bf45208735d22f4e:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$handleEventFromOperator$1(SourceCoordinator.java:172) ~[flink-dist_2.11-1.13.6.jar:1.13.6]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:344) ~[flink-dist_2.11-1.13.6.jar:1.13.6]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_361]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_361]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_361]
Caused by: java.lang.NullPointerException
	at com.ververica.cdc.debezium.history.FlinkJsonTableChangeSerializer.toDocument(FlinkJsonTableChangeSerializer.java:58) ~[blob_p-b4f6d17e0c08bbb487e958e0b3e0e49c0ab04224-e97c463e6ea3a571bf45208735d22f4e:?]
	at com.ververica.cdc.connectors.base.source.meta.split.SourceSplitSerializer.writeTableSchemas(SourceSplitSerializer.java:183) ~[blob_p-b4f6d17e0c08bbb487e958e0b3e0e49c0ab04224-e97c463e6ea3a571bf45208735d22f4e:?]
	at com.ververica.cdc.connectors.base.source.meta.split.SourceSplitSerializer.serialize(SourceSplitSerializer.java:80) ~[blob_p-b4f6d17e0c08bbb487e958e0b3e0e49c0ab04224-e97c463e6ea3a571bf45208735d22f4e:?]
	at com.ververica.cdc.connectors.base.source.meta.split.SourceSplitSerializer.serialize(SourceSplitSerializer.java:44) ~[blob_p-b4f6d17e0c08bbb487e958e0b3e0e49c0ab04224-e97c463e6ea3a571bf45208735d22f4e:?]
	at org.apache.flink.runtime.source.event.AddSplitEvent.<init>(AddSplitEvent.java:44) ~[flink-dist_2.11-1.13.6.jar:1.13.6]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinatorContext.lambda$null$2(SourceCoordinatorContext.java:198) ~[flink-dist_2.11-1.13.6.jar:1.13.6]
	at java.util.HashMap.forEach(HashMap.java:1290) ~[?:1.8.0_361]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinatorContext.lambda$assignSplits$3(SourceCoordinatorContext.java:191) ~[flink-dist_2.11-1.13.6.jar:1.13.6]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinatorContext.callInCoordinatorThread(SourceCoordinatorContext.java:386) ~[flink-dist_2.11-1.13.6.jar:1.13.6]
	... 9 more

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by ysq5202121** [comment]
都有这个问题

**Comment by GOODBOY008** [comment]
@ysq5202121 @edmond-kk Would help me reproduct or locate this issue ?

**Comment by edmond-kk** [comment]
> @ysq5202121 @edmond-kk Would you help me reproduct or locate this issue ?

Of course, I can do that. I have a savepoint that reproduces this bug, and I can consistently reproduce it when recovering from the savepoint. However, I'm not sure how to pinpoint the issue. How can I assist you?

**Comment by edmond-kk** [comment]
> @ysq5202121 @edmond-kk Would you help me reproduct or locate this issue ?

This is an intermittent bug that occurs during the incremental snapshot phase. I can't reproduce it reliably, but I can provide the code. How can I assist you?

**Comment by GOODBOY008** [comment]
@ysq5202121 I would give you my repo with a branch which try to solve this , you can compile and replace for test. Can you help me ?

**Comment by edmond-kk** [comment]
@GOODBOY008  Alright, I'll give it a try. By the way, which bug is this branch attempting to address? Is it the 【Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: 为过程或函数 cdc.fn_cdc_get_all_changes_ ... 提供的参数数目不足】, or is it the bug related to the inability to recover from a savepoint? The former occurs frequently, while I've only encountered the latter twice, and I can't guarantee reproducibility for it.

**Comment by GOODBOY008** [comment]
> @GOODBOY008 Alright, I'll give it a try. By the way, which bug is this branch attempting to address? Is it the 【Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: 为过程或函数 cdc.fn_cdc_get_all_changes_ ... 提供的参数数目不足】, or is it the bug related to the inability to recover from a savepoint? The former occurs frequently, while I've only encountered the latter twice, and I can't guarantee reproducibility for it.

Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: 为过程或函数 cdc.fn_cdc_get_all_changes_ ... 提供的参数数目不足

**Comment by GOODBOY008** [comment]
@edmond-kk Hi, Can this branch solve this issue?

**Comment by edmond-kk** [comment]
@GOODBOY008  I'm not sure, so far I haven't encountered the '为过程或函数 cdc.fn_cdc_get_all_changes_ ... 提供的参数数目不足_...', but the program keeps restarting due to the 'Caused by: java.lang.NullPointerException
at com.ververica.cdc.debezium.history.FlinkJsonTableChangeSerializer.toDocument' that I mentioned earlier. I need to verify this further.

**Comment by GOODBOY008** [comment]
> @GOODBOY008 I'm not sure, so far I haven't encountered the '为过程或函数 cdc.fn_cdc_get_all_changes_ ... 提供的参数数目不足_...', but the program keeps restarting due to the 'Caused by: java.lang.NullPointerException

Can u show me your sql and table ?

**Comment by edmond-kk** [comment]
@GOODBOY008 Sure, how can I send it to you? This is an internal company table.

**Comment by GOODBOY008** [comment]
@edmond-kk BTW, After 2.5.0 will not support flink 1.13.* . Can u try on newer version?

**Comment by edmond-kk** [comment]
@GOODBOY008  Understood, I will try to upgrade later. However, our tasks are about to go live, and we need to validate the stability of the new version of Flink. So, we may not be able to make the switch immediately.

**Comment by GOODBOY008** [comment]
@edmond-kk You just paster table metadata and sql. I will try to reproduce.

**Comment by GOODBOY008** [comment]
@edmond-kk I cannot reproduce on my local , Can you follow `sqlserver-quickstart` run a simply demo ?

**Comment by edmond-kk** [comment]
@GOODBOY008  ok, I'll try. BTW, I haven't encountered the "为过程或函数 cdc.fn_cdc_get_all_changes_ ..." error in the tasks I've been running for the past two days, I think this bug has been resolved.

**Comment by GOODBOY008** [comment]
> @GOODBOY008 ok, I'll try. BTW, I haven't encountered the "为过程或函数 cdc.fn_cdc_get_all_changes_ ..." error in the tasks I've been running for the past two days, I think this bug has been resolved.

Thank you for support me to confirm this.

**Comment by ysq5202121** [comment]
@GOODBOY008  nice,很好

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
