### ISSUE TITLE
The main method caused an error: Invalid metadata key 'row_kind' in column 'operation' of table 

### ISSUE THREAD

**Issue by KONEONE** [apache/flink-cdc#3117]
我正在运行如下sql：
```sql

CREATE TABLE IF NOT EXISTS test_table (
    db_name       STRING METADATA FROM 'database_name' VIRTUAL,
    table_name    STRING METADATA FROM 'table_name' VIRTUAL,
    operation_ts  TIMESTAMP_LTZ(3) METADATA FROM 'op_ts' VIRTUAL,
    operation     STRING METADATA FROM 'row_kind' VIRTUAL,
    id BIGINT NOT NULL COMMENT '编号',
    PRIMARY KEY ( id ) NOT ENFORCED
) WITH (
    'connector' = 'mysql-cdc',
    'hostname' = 'localhost',
    'port' = '3306',
    'username' = 'root',
    'password' = '123456',
    'database-name' = 'mydb',
    'table-name' = 'test'
);

```

![image](https://github.com/apache/flink-cdc/assets/39909636/9bcb9fba-aecc-4592-aa78-ec75539ec4be)
在上面已经存在mysql-cdc:3.0.1了， 想要去获取row_kind字段，但是报错：
```text
Caused by: org.apache.flink.client.deployment.application.ApplicationExecutionException: Could not execute application.
	... 13 more
Caused by: org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: Invalid metadata key 'row_kind' in column 'operation' of table 'default_catalog.default_database.gmall_cart_info'. The DynamicTableSource class 'com.ververica.cdc.connectors.mysql.table.MySqlTableSource' supports the following metadata keys for reading:
table_name
database_name
op_ts
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:372) ~[flink-dist-1.16.3.jar:1.16.3]
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:222) ~[flink-dist-1.16.3.jar:1.16.3]
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:98) ~[flink-dist-1.16.3.jar:1.16.3]
	at org.apache.flink.client.deployment.application.ApplicationDispatcherBootstrap.runApplicationEntryPoint(ApplicationDispatcherBootstrap.java:301) ~[flink-dist-1.16.3.jar:1.16.3]
	... 12 more
Caused by: org.apache.flink.table.api.ValidationException: Invalid metadata key 'row_kind' in column 'operation' of table 'default_catalog.default_database.gmall_cart_info'. The DynamicTableSource class 'com.ververica.cdc.connectors.mysql.table.MySqlTableSource' supports the following metadata keys for reading:
table_name
database_name
op_ts
````

难道是需要如下版本才可以吗？
```xml
<dependency>
  <groupId>com.ververica</groupId>
  <artifactId>flink-connector-mysql-cdc</artifactId>
  <!-- 请使用已发布的版本依赖，snapshot版本的依赖需要本地自行编译。 -->
  <version>3.0-SNAPSHOT</version>
</dependency>
```

**Comment by VincentYuuu** [comment]
I use the flink-connector-mysql-cdc version 3.0.1, ran into the same issue. 
Can anyone check this please?

**Comment by KONEONE** [comment]
> I use the `flink-connector-mysql-cdc version 3.0.1`, ran into the same issue. Can anyone check this please?
I once reported this issue in the official group chat, but did not get any feedback.

**Comment by KONEONE** [comment]
> I use the `flink-connector-mysql-cdc version 3.0.1`, ran into the same issue. Can anyone check this please?

I once reported this issue in the official group chat, but did not get any feedback.

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Comment by duanjianSnail** [comment]
You mentioned that instead of flink-connector-mysql-cdc, one should use flink-sql-connector-mysql-cdc. And i confirmed that flink-sql-connector-mysql-cdc-3.1.1 includes the row_kind feature, and also suggested trying flink-sql-connector-mysql-cdc-3.0.1

**Comment by Mr-hangge** [comment]
// 2. 获取 Changelog 流并过滤 DELETE 事件
    val deleteStream = tEnv
      .toChangelogStream(tEnv.from("ACT_RU_TASK"))  // 获取原始变更流
      .filter(row => row.getKind == RowKind.DELETE)
      .map { row: Row =>
        val id = row.getFieldAs[String]("ID_")
        ("ID_", id)  // 返回 (字段名, 主键值)
      }(TypeInformation.of(classOf[(String, String)]))
