### ISSUE TITLE
mysql同步到starrocks时，当主键是bigint且有无符号时，会被识别为decimal类型，导致创建表失败

### ISSUE THREAD

**Issue by TPSHION** [apache/flink-cdc#3120]
异常信息：
2024-03-09 20:00:20,014 ERROR com.starrocks.connector.flink.catalog.StarRocksCatalog       [] - Failed to create table secret.secret, sql: CREATE TABLE IF NOT EXISTS `secret`.`st_user_gift` (
`id` DECIMAL(20, 0) NOT NULL,
`giftId` VARCHAR(150) NOT NULL,
`uid` DECIMAL(20, 0) NOT NULL,
`num` INT NOT NULL,
`remain` INT NOT NULL,
`getSource` VARCHAR(300) NOT NULL,
`createTime` DATETIME NOT NULL
) PRIMARY KEY (`id`)
DISTRIBUTED BY HASH (`id`)
PROPERTIES (
"fast_schema_evolution" = "true"
);
java.sql.SQLSyntaxErrorException: Getting analyzing error. Detail message: primary key column[id] type not supported: decimal(20, 0).
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[?:?]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[?:?]
	at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1335) ~[?:?]
	at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2084) ~[?:?]
	at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1246) ~[?:?]
	at com.starrocks.connector.flink.catalog.StarRocksCatalog.executeUpdateStatement(StarRocksCatalog.java:470) ~[?:?]
	at com.starrocks.connector.flink.catalog.StarRocksCatalog.createTable(StarRocksCatalog.java:250) ~[?:?]
	at com.ververica.cdc.connectors.starrocks.sink.StarRocksMetadataApplier.applyCreateTable(StarRocksMetadataApplier.java:97) ~[?:?]
	at com.ververica.cdc.connectors.starrocks.sink.StarRocksMetadataApplier.applySchemaChange(StarRocksMetadataApplier.java:71) ~[?:?]
	at com.ververica.cdc.runtime.operators.schema.coordinator.SchemaRegistryRequestHandler.applySchemaChange(SchemaRegistryRequestHandler.java:82) ~[?:?]

**Comment by ihadoop** [comment]
i want to fix this issue

**Comment by loserwang1024** [comment]
Flink only have bigint type, if mysql data is unsigned bigint , maybe out of range, so cast to DECIMAL(20, 0).

**Comment by TPSHION** [comment]
所以只能修改表结构吗？

| |
chen
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Hongshun ***@***.***> |
| 发送日期 | 2024年03月15日 11:50 |
| 收件人 | apache/flink-cdc ***@***.***> |
| 抄送人 | jack ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [apache/flink-cdc] mysql同步到starrocks时，当主键是bigint且有无符号时，会被识别为decimal类型，导致创建表失败 (Issue #3120) |

Flink only have bigint type, if mysql data is unsigned bigint , maybe out of range, so cast to DECIMAL(20, 0).

**Comment by loserwang1024** [comment]
If starrocks supports unsigned bigint, maybe can transform DECIMAL(20, 0) to unsigned bigint in sink.

**Comment by loserwang1024** [comment]
I have added it in jira https://issues.apache.org/jira/browse/FLINK-34690

**Comment by TPSHION** [comment]
额外问个问题，当修改yaml文件时，需要取消任务，再次提交任务后，还会再走之前的同步流程吗？我已经同步好的数据会不会有得重新入库，比较耗费资源

| |
chen
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Hongshun ***@***.***> |
| 发送日期 | 2024年03月15日 12:10 |
| 收件人 | apache/flink-cdc ***@***.***> |
| 抄送人 | jack ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [apache/flink-cdc] mysql同步到starrocks时，当主键是bigint且有无符号时，会被识别为decimal类型，导致创建表失败 (Issue #3120) |

I have added it in jira https://issues.apache.org/jira/browse/FLINK-34690

**Comment by loserwang1024** [comment]
@TPSHION it's hard to say, which depends on whether state is compatibility. If only change some config, it's no problem.But if the pipeline is changes, maybe not restore from state.

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
