### ISSUE TITLE
mysql同步到StarRocks时，如果StarRocks和flink不是同一台服务器时，同步失败

### ISSUE THREAD

**Issue by TPSHION** [apache/flink-cdc#3122]
提示需要连接本地的8040端口。
异常日志：
Caused by: java.lang.RuntimeException: com.starrocks.streamload.shade.org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:8040 [/127.0.0.1] failed: Connection refused (Connection refused)
	at com.starrocks.data.load.stream.TransactionStreamLoader.rollback(TransactionStreamLoader.java:341)
	at com.starrocks.data.load.stream.DefaultStreamLoader.rollback(DefaultStreamLoader.java:254)
	at com.starrocks.data.load.stream.v2.StreamLoadManagerV2.AssertNotException(StreamLoadManagerV2.java:425)
	at com.starrocks.data.load.stream.v2.StreamLoadManagerV2.flush(StreamLoadManagerV2.java:355)
	at com.starrocks.connector.flink.table.sink.v2.StarRocksWriter.flush(StarRocksWriter.java:153)
	at org.apache.flink.streaming.runtime.operators.sink.SinkWriterOperator.prepareSnapshotPreBarrier(SinkWriterOperator.java:168)
	at com.ververica.cdc.runtime.operators.sink.DataSinkWriterOperator.prepareSnapshotPreBarrier(DataSinkWriterOperator.java:160)
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.prepareSnapshotPreBarrier(RegularOperatorChain.java:89)
	at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.checkpointState(SubtaskCheckpointCoordinatorImpl.java:322)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$performCheckpoint$15(StreamTask.java:1318)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.runThrowing(StreamTaskActionExecutor.java:50)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.performCheckpoint(StreamTask.java:1306)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.triggerCheckpointOnBarrier(StreamTask.java:1263)
	... 22 more

**Comment by liisaxin** [comment]
the same question

**Comment by ihadoop** [comment]
it looks config parameters error

**Comment by PatrickRen** [comment]
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
