### ISSUE TITLE
SQL Server does not support scan. startup. mode: initial only

### ISSUE THREAD

**Issue by ysq5202121** [apache/flink-cdc#3290]
'scan.startup.mode'='initial_only'
Error log:
Caused by: org.apache.flink.table.api.ValidationException: Invalid value for option 'scan.startup.mode'. Supported values are [initial, latest-offset], but was: initial_only
	at com.ververica.cdc.connectors.sqlserver.table.SqlServerTableFactory.getStartupOptions(SqlServerTableFactory.java:228)
	at com.ververica.cdc.connectors.sqlserver.table.SqlServerTableFactory.createDynamicTableSource(SqlServerTableFactory.java:124)
	at org.apache.flink.table.factories.FactoryUtil.createDynamicTableSource(FactoryUtil.java:164)
Set to
'debezium.snapshot.mode' = 'initial_only'
No effect

**Comment by yuxiqian** [comment]
Hi @ysq5202121, Flink CDC uses [JIRA](https://issues.apache.org/jira/projects/FLINK/summary) to track new feature requests and deficiencies, not GitHub Issues. Could you please close this issue, open a JIRA ticket to describe your problem there? Thanks!

**Comment by ysq5202121** [comment]
OK
