### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: 'void org.apache.flink.streaming.runtime.operators.sink.CommitterOperatorFactory.<init>(org.apache.flink.api.connector.sink2.TwoPhaseCommittingSink, boolean, boolean)'

### ISSUE THREAD

**Issue by lixiang8103** [apache/flink-cdc#3327]
### Please don't check the box below

- [X] I'm aware that bugs and new features should be reported on Apache Jira or Flink mailing list instead of here

### Again, please don't check the box below

- [X] I'm aware that new issues on GitHub will be ignored and automatically closed.

### 请不要勾选以下选项

- [X] 我已知悉缺陷和新功能需要在 Apache Jira 或 Flink 邮件列表中反馈，而不是在这里创建新 issue。

### 也请不要勾选以下选项

- [X] 我已知悉 GitHub 上的新 issue 会被忽略且自动关闭。

**Comment by lixiang8103** [comment]
`[root@iZbp1h3h5m4ois5qs0bupuZ flink-cdc-3.2-SNAPSHOT]# ./bin/flink-cdc.sh mysql-to-starrocks.yaml 
Exception in thread "main" java.lang.NoSuchMethodError: 'void org.apache.flink.streaming.runtime.operators.sink.CommitterOperatorFactory.<init>(org.apache.flink.api.connector.sink2.TwoPhaseCommittingSink, boolean, boolean)'
	at org.apache.flink.cdc.composer.flink.translator.DataSinkTranslator.addCommittingTopology(DataSinkTranslator.java:137)
	at org.apache.flink.cdc.composer.flink.translator.DataSinkTranslator.sinkTo(DataSinkTranslator.java:86)
	at org.apache.flink.cdc.composer.flink.translator.DataSinkTranslator.translate(DataSinkTranslator.java:64)
	at org.apache.flink.cdc.composer.flink.FlinkPipelineComposer.compose(FlinkPipelineComposer.java:143)
	at org.apache.flink.cdc.cli.CliExecutor.run(CliExecutor.java:71)
	at org.apache.flink.cdc.cli.CliFrontend.main(CliFrontend.java:71)`

**Comment by yuxiqian** [comment]
Tracked in FLINK-35415. For new feature requests / bug reports, please open a ticket in [Flink JIRA Kanban](https://issues.apache.org/jira/projects/FLINK/summary).
