### ISSUE TITLE
Caused by: java.lang.ClassCastException: cannot assign instance of org.apache.doris.flink.cfg.DorisOptions to field org.apache.flink.cdc.connectors.doris.sink.DorisMetadataApplier.dorisOptions of type org.apache.doris.flink.cfg.DorisOptions in instance of org.apache.flink.cdc.connectors.doris.sink.DorisMetadataApplier

### ISSUE THREAD

**Issue by imbrin1122** [apache/flink-cdc#3406]
Version:
```
mysql:8.0.31
doris-2.1.3-rc09
flink-1.19.0-bin-scala_2.12.tgz
flink-cdc-3.1.0-bin.tar.gz
flink-cdc-pipeline-connector-mysql-3.1.0.jar
flink-cdc-pipeline-connector-doris-3.1.0.jar
mysql-connector-java-8.0.27.jar
```

Doris 3FE and 3BE

mysql-to-doris.yaml 
```
################################################################################
# Description: Sync MySQL all tables to Doris
################################################################################
source:
  type: mysql
  hostname: localhost
  port: 3305
  username: root
  password: 123456
  tables: doris-test.\.*
  server-id: 5400-5404
  server-time-zone: UTC

sink:
  type: doris
  fenodes: localhost:8031
  username: root
  password: ""
  table.create.properties.light_schema_change: true
  table.create.properties.replication_num: 1

pipeline:
  name: Sync MySQL Database to Doris
  parallelism: 2
```

./bin/flink-cdc.sh
```
./bin/flink-cdc.sh mysql-to-doris.yaml 
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/brin/work/tools/doris_build/doris-1fe1be/tools/flink-1.19.0/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/brin/data/doris-runtime/flink/flink-1.19.0/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Exception in thread "main" org.apache.flink.util.FlinkException: Failed to execute job 'Sync MySQL Database to Doris'.
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.executeAsync(StreamExecutionEnvironment.java:2455)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.executeAsync(StreamExecutionEnvironment.java:2421)
	at org.apache.flink.cdc.composer.flink.FlinkPipelineExecution.execute(FlinkPipelineExecution.java:43)
	at org.apache.flink.cdc.cli.CliExecutor.run(CliExecutor.java:74)
	at org.apache.flink.cdc.cli.CliFrontend.main(CliFrontend.java:71)
Caused by: java.lang.RuntimeException: org.apache.flink.runtime.client.JobInitializationException: Could not start the JobMaster.
	at org.apache.flink.util.ExceptionUtils.rethrow(ExceptionUtils.java:321)
	at org.apache.flink.util.function.FunctionUtils.lambda$uncheckedFunction$2(FunctionUtils.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: org.apache.flink.runtime.client.JobInitializationException: Could not start the JobMaster.
	at org.apache.flink.runtime.jobmaster.DefaultJobMasterServiceProcess.lambda$new$0(DefaultJobMasterServiceProcess.java:97)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: org.apache.flink.runtime.JobException: Cannot instantiate the coordinator for operator Source: Flink CDC Event Source: mysql -> SchemaOperator -> PrePartition
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	... 3 more
Caused by: java.lang.RuntimeException: org.apache.flink.runtime.JobException: Cannot instantiate the coordinator for operator Source: Flink CDC Event Source: mysql -> SchemaOperator -> PrePartition
	at org.apache.flink.util.ExceptionUtils.rethrow(ExceptionUtils.java:321)
	at org.apache.flink.util.function.FunctionUtils.lambda$uncheckedSupplier$4(FunctionUtils.java:114)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 3 more
Caused by: org.apache.flink.runtime.JobException: Cannot instantiate the coordinator for operator Source: Flink CDC Event Source: mysql -> SchemaOperator -> PrePartition
	at org.apache.flink.runtime.executiongraph.ExecutionJobVertex.<init>(ExecutionJobVertex.java:182)
	at org.apache.flink.runtime.executiongraph.ExecutionJobVertex$Factory.createExecutionJobVertex(ExecutionJobVertex.java:671)
	at org.apache.flink.runtime.executiongraph.DefaultExecutionGraph.attachJobVertices(DefaultExecutionGraph.java:860)
	at org.apache.flink.runtime.executiongraph.DefaultExecutionGraph.attachJobGraph(DefaultExecutionGraph.java:833)
	at org.apache.flink.runtime.executiongraph.DefaultExecutionGraphBuilder.buildGraph(DefaultExecutionGraphBuilder.java:221)
	at org.apache.flink.runtime.scheduler.DefaultExecutionGraphFactory.createAndRestoreExecutionGraph(DefaultExecutionGraphFactory.java:173)
	at org.apache.flink.runtime.scheduler.SchedulerBase.createAndRestoreExecutionGraph(SchedulerBase.java:381)
	at org.apache.flink.runtime.scheduler.SchedulerBase.<init>(SchedulerBase.java:224)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.<init>(DefaultScheduler.java:140)
	at org.apache.flink.runtime.scheduler.DefaultSchedulerFactory.createInstance(DefaultSchedulerFactory.java:162)
	at org.apache.flink.runtime.jobmaster.DefaultSlotPoolServiceSchedulerFactory.createScheduler(DefaultSlotPoolServiceSchedulerFactory.java:121)
	at org.apache.flink.runtime.jobmaster.JobMaster.createScheduler(JobMaster.java:379)
	at org.apache.flink.runtime.jobmaster.JobMaster.<init>(JobMaster.java:356)
	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.internalCreateJobMasterService(DefaultJobMasterServiceFactory.java:128)
	at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.lambda$createJobMasterService$0(DefaultJobMasterServiceFactory.java:100)
	at org.apache.flink.util.function.FunctionUtils.lambda$uncheckedSupplier$4(FunctionUtils.java:112)
	... 4 more
Caused by: java.lang.ClassCastException: cannot assign instance of org.apache.doris.flink.cfg.DorisOptions to field org.apache.flink.cdc.connectors.doris.sink.DorisMetadataApplier.dorisOptions of type org.apache.doris.flink.cfg.DorisOptions in instance of org.apache.flink.cdc.connectors.doris.sink.DorisMetadataApplier
	at java.base/java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2102)
	at java.base/java.io.ObjectStreamClass$FieldReflector.checkObjectFieldValueTypes(ObjectStreamClass.java:2066)
	at java.base/java.io.ObjectStreamClass.checkObjFieldValueTypes(ObjectStreamClass.java:1355)
	at java.base/java.io.ObjectInputStream$FieldValues.defaultCheckFieldValues(ObjectInputStream.java:2682)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2483)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2269)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1747)
	at java.base/java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2603)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2454)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2269)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1747)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:525)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:483)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:539)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:527)
	at org.apache.flink.util.SerializedValue.deserializeValue(SerializedValue.java:67)
	at org.apache.flink.runtime.operators.coordination.OperatorCoordinatorHolder.create(OperatorCoordinatorHolder.java:496)
	at org.apache.flink.runtime.executiongraph.ExecutionJobVertex.createOperatorCoordinatorHolder(ExecutionJobVertex.java:294)
	at org.apache.flink.runtime.executiongraph.ExecutionJobVertex.<init>(ExecutionJobVertex.java:173)
	... 19 more

```

**Comment by leonardBang** [comment]
As required by Apache Flink, please report bugs or new features on [Apache Jira](https://issues.apache.org/jira)
under the project Flink using component tag Flink CDC. You must have a JIRA account in order to log cases and issues.
If you don’t have an ASF JIRA account, you can request one at the [ASF Self-serve portal](https://selfserve.apache.org/jira-account.html),
account creation requires review by the PMC member of the application project, which normally takes one to two working days to be approved.

**Comment by jwh0923** [comment]
did this question figure out,I meet the same bug.but I use the version of flink is 1.18

**Comment by jwh0923** [comment]
在dinky使用的Cdc版本不一样 导致的



---Original---
From: ***@***.***&gt;
Date: Thu, Nov 21, 2024 09:40 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/flink-cdc] Caused by: java.lang.ClassCastException:cannot assign instance of org.apache.doris.flink.cfg.DorisOptions to fieldorg.apache.flink.cdc.connectors.doris.sink.DorisMetadataApplier.dorisOptionsof type org.apache.doris.flink.cfg.DorisOptions in instance oforg.apache.flink.cdc.connectors.doris.sink.DorisMetadataApplier (Issue #3406)




 
遇到同一个问题了

**Comment by wuzhaoyu** [comment]
如何解决的 为什么issue closed

**Comment by guojiew** [comment]
dinky 1.2.0
flink 1.18
flink cdc 3.2.1/3.2.0 
碰到同样问题。这个issue连回答都懒得回答就直接关闭？这就是kpi吗，太秀了。。

**Comment by guojiew** [comment]
Just a reminder for all the guys who encounter the same problem. 
The pipeline-doris jar package of version 3.2.x is a fat jar, which has shaded the classes of flink-doris-connector. Please delete all the files under org/apache/doris in the pipeline-doris fat jar and repackage it, and then put it into the dependency directory of Dinky.

**Comment by leonardBang** [comment]
Please refer https://github.com/apache/flink-cdc/issues/3814 for more information

**Comment by tianmingxing** [comment]
Temporary solution:

```bash
1. rm lib/flink-cdc-pipeline-connector-doris-3.5.0.jar
2. ./bin/stop-cluster.sh
3. ./bin/start-cluster.sh
3. cp ~/flink-cdc-pipeline-connector-doris-3.5.0.jar lib/
4. ./bin/flink-cdc.sh ./cdc_pipeline/mysql-to-doris.yaml
   Pipeline has been submitted to cluster.
   Job ID: bb42dc37b41df965294f256986d35920
   Job Description: Sync MySQL Database to Doris
```

**Comment by xiaomlove** [comment]
> Temporary solution:
> 
> 1. rm lib/flink-cdc-pipeline-connector-doris-3.5.0.jar
> 2. ./bin/stop-cluster.sh
> 3. ./bin/start-cluster.sh
> 3. cp ~/flink-cdc-pipeline-connector-doris-3.5.0.jar lib/
> 4. ./bin/flink-cdc.sh ./cdc_pipeline/mysql-to-doris.yaml
>    Pipeline has been submitted to cluster.
>    Job ID: bb42dc37b41df965294f256986d35920
>    Job Description: Sync MySQL Database to Doris

可以解决，但实际原因是什么？

**Comment by sanmen359** [comment]
# flink-conf.yaml
classloader.resolve-order: parent-first
classloader.parent-first-patterns.additional: org.apache.doris;org.apache.flink.cdc.connectors.doris
