### ISSUE TITLE
flink-cdc3.x版本不支持同步MySQL含有联合主键的表到doris中，任务会报异常并且停止

### ISSUE THREAD

**Issue by BambooJWB** [apache/flink-cdc#3759]
### Please don't check the box below

- [X] I'm aware that bugs and new features should be reported on [Apache Jira](https://issues.apache.org/jira)  or Flink mailing list (dev@flink.apache.org) instead of here

### Again, please don't check the box below

- [X] I'm aware that new issues on GitHub will be ignored and automatically closed.

### 请不要勾选以下选项

- [X] 我已知悉缺陷和新功能需要在 [Apache Jira](https://issues.apache.org/jira) 或 Flink 邮件列表（dev@flink.apache.org）中反馈，而不是在这里创建新 issue。

### 也请不要勾选以下选项

- [ ] 我已知悉 GitHub 上的新 issue 会被忽略且自动关闭。

**Comment by BambooJWB** [comment]
Caused by: org.apache.flink.table.api.ValidationException: Chunk key column 'id,dep_code' doesn't exist in the primary keys [id,dep_code] of the table bkqw_loan.uc_syn_department.
at org.apache.flink.cdc.connectors.mysql.source.utils.ChunkUtils.getChunkKeyColumn(ChunkUtils.java:81) ~[flink-sql-connector-mysql-cdc-3.1.0.jar:3.1.0]
at org.apache.flink.cdc.connectors.mysql.source.assigners.MySqlChunkSplitter.analyzeTable(MySqlChunkSplitter.java:149) ~[flink-sql-connector-mysql-cdc-3.1.0.jar:3.1.0]
at org.apache.flink.cdc.connectors.mysql.source.assigners.MySqlChunkSplitter.splitChunks(MySqlChunkSplitter.java:116) ~[flink-sql-connector-mysql-cdc-3.1.0.jar:3.1.0]
at org.apache.flink.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.splitTable(MySqlSnapshotSplitAssigner.java:304) ~[flink-sql-connector-mysql-cdc-3.1.0.jar:3.1.0]
at org.apache.flink.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.splitChunksForRemainingTables(MySqlSnapshotSplitAssigner.java:568) ~[flink-sql-connector-mysql-cdc-3.1.0.jar:3.1.0]

**Comment by BambooJWB** [comment]
目前生产环境中MySQL用的是8.x，doris用的2.0.3版本，需要同步的MySQL表一共有三十多张表，其中有且仅有一张表是使用联合主键，其他表均是单字段唯一主键。第一次启动时正常的，数据能够同步到doris中，但是一旦有操作修改了这个联合主键的表，整个cdc会直接抛出异常并且导致整个cdc任务失败并且不断的重启。

**Comment by BambooJWB** [comment]
![image](https://github.com/user-attachments/assets/a46bdbcd-7e0c-441e-8a0e-30142b0fa1fe)

**Comment by yuxiqian** [comment]
Resolved in #3448. Try upgrading to 3.2.0.
