### ISSUE TITLE
java.lang.IllegalStateException: Unable to get latest schema

### ISSUE THREAD

**Issue by najsword** [apache/flink-cdc#3798]
### Please don't check the box below

- [X] I'm aware that bugs and new features should be reported on [Apache Jira](https://issues.apache.org/jira)  or Flink mailing list (dev@flink.apache.org) instead of here

### Again, please don't check the box below

- [X] I'm aware that new issues on GitHub will be ignored and automatically closed.

### 请不要勾选以下选项

- [X] 我已知悉缺陷和新功能需要在 [Apache Jira](https://issues.apache.org/jira) 或 Flink 邮件列表（dev@flink.apache.org）中反馈，而不是在这里创建新 issue。

### 也请不要勾选以下选项

- [X] 我已知悉 GitHub 上的新 issue 会被忽略且自动关闭。

**Comment by najsword** [comment]
Error: Unable to get latest schema for table && Caused by: java.lang.IllegalStateException: Schema doesn't exist fo

Purpose: mysql->doris sync work.  

Detail:
2024-12-13 16:54:40
java.lang.IllegalStateException: Unable to get latest schema for table "jifei_gdznsjk_smp.acr_record_1006_202007"
at org.apache.flink.cdc.runtime.operators.schema.SchemaOperator.getLatestEvolvedSchema(SchemaOperator.java:530)
at org.apache.flink.cdc.runtime.operators.schema.SchemaOperator.lambda$processSchemaChangeEvents$1(SchemaOperator.java:280)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.apache.flink.cdc.runtime.operators.schema.SchemaOperator.processSchemaChangeEvents(SchemaOperator.java:280)
at org.apache.flink.cdc.runtime.operators.schema.SchemaOperator.processElement(SchemaOperator.java:255)
at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:75)
at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:50)
at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:29)
at org.apache.flink.streaming.runtime.tasks.SourceOperatorStreamTask$AsyncDataOutputToOutput.emitRecord(SourceOperatorStreamTask.java:310)
at org.apache.flink.streaming.api.operators.source.SourceOutputWithWatermarks.collect(SourceOutputWithWatermarks.java:110)
at org.apache.flink.streaming.api.operators.source.SourceOutputWithWatermarks.collect(SourceOutputWithWatermarks.java:101)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.apache.flink.cdc.connectors.mysql.source.reader.MySqlPipelineRecordEmitter.processElement(MySqlPipelineRecordEmitter.java:117)
at org.apache.flink.cdc.connectors.mysql.source.reader.MySqlRecordEmitter.emitRecord(MySqlRecordEmitter.java:73)
at org.apache.flink.cdc.connectors.mysql.source.reader.MySqlRecordEmitter.emitRecord(MySqlRecordEmitter.java:46)
at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:203)
at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:422)
at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:68)
at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65)
at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:638)
at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:231)
at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:973)
at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:917)
at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:970)
at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:949)
at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:763)
at org.apache.flink.runtime.taskmanager.Task.run(Task.java:575)
at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalStateException: Schema doesn't exist for table "jifei_gdznsjk_smp.acr_record_1006_202007"
at org.apache.flink.cdc.runtime.operators.schema.SchemaOperator.getLatestEvolvedSchema(SchemaOperator.java:525)
... 27 more

**Comment by najsword** [comment]
Problem: Unable to get latest schema for table && Caused by: java.lang.IllegalStateException: Schema doesn't exist fo

Purpose: mysql->doris sync. About Billion data.

Tool:  mysql-5.6.46/5.7.23-log   doris-3.0.1-rc04-patch1-8c4e5730a1   flink-1.20.0  flick-cdc-3.2.1&yaml

Explain: this table is exist in doris. Usually Happen this Error.  How to slove it !!!

Detail:
2024-12-13 16:54:40
java.lang.IllegalStateException: Unable to get latest schema for table "jifei_xxxx"
at org.apache.flink.cdc.runtime.operators.schema.SchemaOperator.getLatestEvolvedSchema(SchemaOperator.java:530)
at org.apache.flink.cdc.runtime.operators.schema.SchemaOperator.lambda$processSchemaChangeEvents$1(SchemaOperator.java:280)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.apache.flink.cdc.runtime.operators.schema.SchemaOperator.processSchemaChangeEvents(SchemaOperator.java:280)
at org.apache.flink.cdc.runtime.operators.schema.SchemaOperator.processElement(SchemaOperator.java:255)
at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:75)
at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:50)
at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.collect(CopyingChainingOutput.java:29)
at org.apache.flink.streaming.runtime.tasks.SourceOperatorStreamTask$AsyncDataOutputToOutput.emitRecord(SourceOperatorStreamTask.java:310)
at org.apache.flink.streaming.api.operators.source.SourceOutputWithWatermarks.collect(SourceOutputWithWatermarks.java:110)
at org.apache.flink.streaming.api.operators.source.SourceOutputWithWatermarks.collect(SourceOutputWithWatermarks.java:101)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.apache.flink.cdc.connectors.mysql.source.reader.MySqlPipelineRecordEmitter.processElement(MySqlPipelineRecordEmitter.java:117)
at org.apache.flink.cdc.connectors.mysql.source.reader.MySqlRecordEmitter.emitRecord(MySqlRecordEmitter.java:73)
at org.apache.flink.cdc.connectors.mysql.source.reader.MySqlRecordEmitter.emitRecord(MySqlRecordEmitter.java:46)
at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:203)
at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:422)
at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:68)
at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65)
at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:638)
at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:231)
at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:973)
at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:917)
at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:970)
at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:949)
at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:763)
at org.apache.flink.runtime.taskmanager.Task.run(Task.java:575)
at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalStateException: Schema doesn't exist for table "jifei_xxx"
at org.apache.flink.cdc.runtime.operators.schema.SchemaOperator.getLatestEvolvedSchema(SchemaOperator.java:525)
... 27 more
